main/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from main.views import *

app_name ='main'
urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('submit/', ProcessAssignmentView.as_view(), name='submit'),
	path('submit-assignment/', SubmitAssignmentView.as_view(), name='submit-assignment'),
	path('success/', SuccessAssignmentView.as_view(), name='submit-success'),

	path('reviews/', ReviewsView.as_view(), name='reviews'),
	path('review-submit/', ProcessReviews.as_view(), name='submit-reviews'),

	path('services/', ServicesView.as_view(), name='services'),
	
	path('samples/', SamplesView.as_view(), name='samples'),
	path('samples/<slug>', SamplesDetailView.as_view(), name='samples_detail'),
	path('search_sample/', SampleSearchView.as_view(), name='search_sample'), # process the search sample input field

	path('experts/', ExpertsView.as_view(), name='experts'),
	path('questions/', QuestionsView.as_view(), name='questions'),

	path('<str:filename>/', download_file, name='download'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uaeass/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main"))
]

main/models.py
import os

from django.db import models

# Create your models here.
OPTIONS = (
	(1, 1),
	(2, 2),
	(3, 3),
	(4, 4),
	(5, 5),
)


class Assignment(models.Model):
	full_name = models.CharField(max_length=255, blank=False, null=False)
	email = models.EmailField(max_length=255)
	country = models.CharField(max_length=255, blank=False, null=False)
	phone = models.CharField(max_length=255, blank=False)
	subject = models.CharField(max_length=255, blank=False)
	deadline = models.DateTimeField(auto_now=True)
	education_level = models.CharField(max_length=255, blank=False)
	referencing_style = models.CharField(max_length=255, blank=False)
	paper_type = models.CharField(max_length=255, blank=False)
	paper_length = models.CharField(max_length=255, blank=False)
	question = models.TextField()
	word_count = models.CharField(max_length=255, blank=False, default='')

	file = models.FileField(upload_to='documents/', blank=True, null=True)
	
	class Meta:
		ordering = ('id',)

	def __str__(self) -> str:
		return f'Assignment({self.full_name})'

	__repr__ = __str__

	# .. more helpers below 


class Review(models.Model):
	title = models.CharField(max_length=256)
	name = models.CharField(max_length=256)
	qualification = models.CharField(max_length=256)
	# assignment_id = models.CharField(max_length=256)
	star = models.IntegerField(choices=OPTIONS)	
	description = models.TextField()
	
	class Meta:
		ordering = ('id',)

	def __str__(self) -> str:
		return self.title

	__repr__ = __str__


class Sample(models.Model):
	heading = models.CharField(max_length=256)
	subject = models.CharField(max_length=256)
	description = models.TextField(blank=True, null=True)
	slug = models.SlugField(max_length=250, default='')
	url = models.CharField(max_length=256, blank=True, null=True, default='')

	class Meta:
		ordering = ('id',)

	def __str__(self) -> str:
		return self.heading

	__repr__ = __str__


class SampleMultipleFile(models.Model):
	file = models.FileField(upload_to='samples/')
	sample = models.ForeignKey(Sample, on_delete=models.CASCADE, related_name='samples')

	def __str__(self) -> str:
		return os.path.split(self.file.name)[-1]

	__repr__ = __str__


class Question(models.Model):
	category = models.CharField(max_length=256)
	date = models.DateField(blank=True, null=True)
	description = models.TextField()
	# TODO: add an images fields  

	def __str__(self) -> str:
		return self.category 

	__repr__ = __str__

main/forms.py
from django import forms 
from django.forms import ClearableFileInput

from main.models import Assignment, Review, Sample

class AssignmentForm(forms.ModelForm):
	class Meta:
		model = Assignment
		fields = '__all__'


class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = '__all__'


class SampleForm(forms.ModelForm):
	class Meta:
		model = Sample
		fields = '__all__'
		widgets = {
            'file': ClearableFileInput(attrs={'multiple': True}),
        }

main/views.py
import mimetypes
import os

from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, TemplateView, FormView, DetailView
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings

from main.forms import AssignmentForm, ReviewForm
from main.models import Review, Sample, Question


class IndexView(TemplateView):
	'''
	The home page and the likes 
	'''
	template_name = 'main/index.html'

	def get_context_data(self, *args, **kwargs):
		return super().get_context_data()


class ProcessAssignmentView(CreateView):
	'''
	Sends email data to the receiver 
	as well as stores in DB. 
	so , definitely, model is required for the form data 
	'''
	template_name = 'main/index.html'
	form_class = AssignmentForm

	def get_success_url(self) -> str:
		'''
		Redirect user to the success page .. 
		'''
		name = self.request.POST.get('full_name', 'Blankee')
		message = f"""{name} just submitted an assignment. login to the admin to check it out now"""
		send_mail('ASSIGNMENT SUBMISSION ON UAEASSIGNMENTWRITERs.COM', message, 'uaeassignmentwriters@uaeassignmentwriters.com', [settings.RECIPIENT])
		return f"{reverse('main:submit-success')}?name={name}"

	def form_invalid(self, form):
		'''
		What do we do if the form is invalid .. ?
		we redirect to the home page 
		'''
		return super().form_invalid(form)


class SuccessAssignmentView(TemplateView):
	'''
	Where users are redirected to after a successful submission 
	'''
	
	template_name = 'main/success.html'

	def get_context_data(self, *args, **kwargs) -> dict:
		'''
		Add whatever relevant message the user might need 
		such as the order ID
		ts = self.request.query_params.get('ts', 0)
		'''
		name = self.request.GET.get('name', 'John Doe')
		return super().get_context_data(name=name, **kwargs)


class ReviewsView(ListView):
	model = Review
	template_name = 'main/reviews.html'
	paginate_by = 5


class ProcessReviews(CreateView):
	template_name = 'main/reviews.html'
	form_class = ReviewForm

	def get_success_url(self) -> str:
		return f"{reverse('main:reviews')}"


class ServicesView(TemplateView):
	template_name = 'main/services.html'


class SamplesView(ListView):
	template_name = 'main/samples.html'
	model = Sample
	paginate_by = 5


class SamplesDetailView(DetailView):
	model = Sample
	template_name = 'main/sample_details.html'


class SampleSearchView(CreateView):
	template_name = 'main/sample_base.html'
	paginate_by = 5

	def post(self, request, *args, **kwargs) -> object:
		search = self.request.POST.get('search')
		if search:
			queryset = Sample.objects.filter(heading__icontains=search)
		else:
			search = self.request.POST.get('categories')
			queryset = Sample.objects.filter(subject__icontains=search)

		return render(request, 'main/samples.html', {'object_list': queryset})


class ExpertsView(TemplateView):
	template_name = 'main/experts.html'


class QuestionsView(ListView):
	model = Question


class SubmitAssignmentView(TemplateView):
	template_name = 'main/submit-assignment.html'


def download_file(request: object, filename: str) -> object:
	BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	filepath = os.path.join(BASE_DIR, os.path.join('media', 'documents'), filename)
	fl = open(filepath, 'rb')
	mimetype, _ = mimetypes.guess_type(filepath)
	response = HttpResponse(fl, content_type=mimetype)
	response['Content-Disposition'] = "attachment; filename=%s" % filename
	return response

templates/main/experts.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

<header class="header">
  <div class="header__text-box">
    <h1 class="display-1 fw-bold text-shadow">Top University Graduates</p>
    <p class="lead fs-3 text-shadow">Proficient in all Assignments</p>
    <p class="lead fs-4 text-shadow">Proficient in 100+ subjects (from English to Nursing)</p>
    <p class="lead fs-4 text-shadow">Familiar with all the formatting styles (MLA, APA, etc.)</p>
  </div>
</header>

<section class="container-fluid py-5 header--section">
  <div class="container pt-5">
    <div class="row pt-5 justify-content-center">
      <div class="col-md-12 col-lg-5">
        <p class="fs-3 fw-bold">The More You Know, The Better</p>
        <p>
          91% of our experts are PhD degree holders
        </p>
        <p class="fw-light">
          Quickest delivery recorded is <strong>2 hours!</strong> 
          It was an urgent 1800-word essay task
          All our experts have at least 7 years experience
          We have experts with excellent skills in academic, research, Linguistics, Literary Analysis, and article writing on different topics.We also have freelancer for penetration tester, focused on web and mobile application security along with programming skills.        
        </p>
      </div>

      <div class="col-md-12 col-lg-5">
        <img class="img-fluid" src="{% static 'images/in stant asignment help.jpg' %}" alt="in stant asignment help.jpg">
      </div>
    </div>
  </div>
</section>

<section class="experts-section">

</section>

{% endblock %}

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
  <div class="back-div bg-dark-blue text-white py-4">
    <main class="container">
      <div class="row justify-content-between">
        
        <div class="col-md-12 col-lg-6 py-1">
          <h1 class="display-3 lh-1 fw-lighter">
            No.1<span class="fw-bold text-blue"> Assignment</span>
            <span class="fw-bold text-blue">Writing Service </span>
          </h1>
          <h1 class="display-3 fw-normal">UAE Freelancers</h1> 
  
          <h3 class="lead text-wrap">Certified Tutors & Writers Service Available Online For UAE Students</h3>

          <hr class="my-4 text-blue">
          <div class="row">
            
            
            <div class="col-3 col-sm-3">
              <span class="fs-1">5000+</span><br>
              <span class="fw-light text-blue">Happy<br>Students</span>
            </div>
            
            <div class="col-3 col-sm-3">
              <span class="fs-1">1000+</span><br>
              <span class="fw-light text-blue">Premium<br>Experts</span>
            </div>
          
            <div class="col-3 col-sm-3">
              <span class="fs-1">200+</span><br>
              <span class="fw-light text-blue">Covered<br>Subjects</span>
            </div>
            
            <div class="col-3 col-sm-2">
              <span class="fs-1">10+</span><br>
              <span class="fw-light lh-1 text-blue">Working together or alliends</span>
            </div>
            
            <div class="col-sm-3">
              <span class="fs-1">10000+</span><br>
              <span class="fw-light lh-1 text-blue">Assignment<br>Deliveries</span>
            </div>
          </div>
      
        </div>

        <div class="col-lg-6 col-md-12 mt-sm-4 mt-3 mt-md-0 mb-3">
          {% include 'main/assignment_form.html' %}
        </div>
      </div>
    </main>
  </div>

  <section class="container-fluid mt-5">
    <div class="container">
      <div class="row justify-content-between mb-5">
        <div class="col-md-12 col-lg-6">
          <p class="h3 text-dark-blue">
            Get Answer To All Your Queries In A Proficient Manner!
          </p>
          <p>
            While assignment writing can be very annoying, considering that college students have to do it all their lives, we have no choice but to get used to it. However, you can either compromise on your peace of mind and complete all the assignments single-handedly or take our professional assignment help in UAE.
            We have a team of highly qualified writers with extensive experience in the field of writing and they are using their smart skills to construct the best assignment papers for you.
            Whether it is a business assignment or science, we have writers from all types of educational backgrounds and qualifications to efficiently construct your papers. 
            <!-- We make sure to assign the assignment to the writer who has the expertise in the subject for which you have ordered the assignment.  -->
            <!-- Additionally, the experience and skills of our writers make it easy for them to provide assignment help to students across Dubai, Sharjah, Abu Dhabi, Al Ain and other major emirates of UAE in the best quality. -->
          </p>
        </div>
        <div class="col-md-12 col-lg-6">
          <img class="img-fluid" src="{% static 'images/assignment proof reading.jpg' %}" alt="assignment proof reading.jpg">
        </div>
      </div>

      <div class="row justify-content-between mb-5">
        <div class="col col-lg-6">
          <p class="h3 text-dark-blue">
            Professional Assignment Writing Services For You To Submit Your Assignment on Time In An Affordable Price!
          </p>
          <p> 
            In college and university, meeting deadlines play the vital role in getting top grades. 
            However, quality cannot be compromised. If you have a very short amount of time left to submit your college
            assignment, reach out to us and we will make sure to construct a top-quality assignment for you in the given time.
            Customer satisfaction is very important for us and therefore, we make sure to deliver all the assignments in the promised time.
             With UAE Writers, you will never have to face late delivery issues until there is a genuine reasoning.
             <!-- Additionally, we also provide urgent assignment writing help in best quality. 
             Whether you want it in 6 hours or 12 hours, our writers are thoroughly experienced to write assignment papers in short deadlines even shorter than 24 hours!  -->
             <!-- Furthermore, we ensure you that timely or last-minute orders delivery availability does not mean that we compromise on the quality as it stays the same! All the assignments are written from scratch according to the specifications mentioned by you and the standard requirements of your institute. We make sure there is no copied or plagiarized data that would put your credibility in jeopardy. For additional satisfaction, we provide you with TurnitIn reports as well! Don’t wait and order your assignment now to impress your teachers! -->
            </p>
          </div>
          <div class="col-md-12 col-lg-6">
            <img class="img-fluid" src="{% static 'images/do my assignmnet.jpg' %}" alt="do my assignmnet.jpg">
          </div>
      </div>

      <div class="row justify-content-between">
        <div class="col-md-12 col-lg-6">
          <p class="h3 text-dark-blue">
            Delivering Quality Assignment Writing Service In UAE With Amazing Reasons To Choose Us!
          </p>
          <p>
            If you are confused about choosing us, let us tell you the additional perks that come with our assignment help. 
            Every order is given careful attention and a proper research is conducted before constructing the assignments and at the time of delivery we make sure to make every assignment worth an A grade.
            <!-- To make that possible, there are several things that you do not need to worry about as you will get it with the assignments without asking for it!<br> -->
            We offer:
          </p>
          <ul>
            <li>Thorough research</li>
            <li>Attention to details</li>
            <li>Free of plagiarism</li>
            <li>Title page and bibliography</li>
            <li>Unlimited free revisions</li>
          </ul>
        </div>
        <div class="col-md-12 col-lg-6">
          <img class="img-fluid" src="{% static 'images/essay writing.jpg' %}" alt="essay writing.jpg">
        </div>
      </div>

    </div>
  </section>

{% endblock %}

templates/main/pagination.html
<nav class="container mt-4">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      </li>
    {% endif %}
    
    {% if paginator.num_pages > 1 %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>  
      </li>
      
      <li class="page-item">
        <span class="page-link">of</span>
      </li>

      <li class="page-item">
        <a class="page-link" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
      </li>
    {% endif %} 

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% endif %}
    </ul>
  </nav>
  

templates/main/question_list.html
{% extends "main/sample_base.html" %}

{% block heading %}Find Solved Questions{% endblock %}

{% block search_by_text %}
<form action="" method="POST">
  <div class="input-group">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Search questions" class="form-control">
    <input type="submit" value="Search" class="btn bg-dark-blue text-light">
  </div>
</form>
{% endblock %}

{% block search_by_dropdown %}
<form action="" method="POST">
  {% csrf_token %}
  <select class="form-select" name="categories" id="categories" onchange="submit_form(this)">
    <option selected>Select Categories</option>
    <option value="Macroeconomics">Macroeconomics</option>
    <option value="Organizational Behavior">Organizational Behavior</option>
    <option value="BBA Leadership">BBA Leadership</option>
    <option value="Strategic Human Resource Management">Strategic Human Resource Management</option>
    <option value="Customer Relationship Management">Customer Relationship Management</option>
    <option value="Training and Developement">Training and Development</option>
    <option value="Facts and Opinions">Facts and Opinions</option>
    <option value="The GCC Economics">The GCC Economics</option>
    <option value="Project Management">Project Management</option>
    <option value="Design Thinking">Design Thinking</option>
    <option value="Business Case">Business Case</option>
    <option value="Managerial Economics">Managerial Economics</option>
    <option value="Contemporary Issues in Strategic Management">Contemporary Issues in Strategic Management</option>
    <option value="Principles of Managerial Accounting">Principles of Managerial Accounting</option>
    <option value="Management Information Systems">Management Information Systems</option>
    <option value="Management">Management</option>
    <option value="HR">HR</option>
    <option value="Accounting">Accounting</option>
    <option value="Marketing">Marketing</option>
    <option value="Leadership">Leadership</option>
    <option value="BSC in Education Lesson Plan">BSC in Education Lesson Plan</option>
    <option value="Legal Aspect of Health Management">Legal Aspect of Health Management</option>
    <option value="CEI Reduce, Reuse and Recycle">CEI Reduce, Reuse and Recycle</option>
    <option value="Change Management">Change Management</option>
    <option value="Critical Review">Critical Review</option>
    <option value="International Perspective on Business">International Perspective on Business</option>
    <option value="Principles of Financial Accounting">Principles of Financial Accounting</option>
    <option value="Interactive Read Aloud">Interactive Read Aloud</option>
  </select>
</form>
{% endblock %}

{% block samples %}
  {% for object in object_list %}
  <div class="card mb-3">
    <div class="card-body">
      {% with object.description as description %}
        {% if description %}
        <p class="card-text">
          <span class="fw-normal">{{ object.date }}</span>
          &verbar;
          {{ description|truncatewords:40 }}
        </p>
        {% endif %}
      {% endwith %}
        <p class="card-title badge bg-dark-blue">{{ object.category|title }}</p>
        <a href="#" class="btn btn-sm float-end text-dark-blue">Read more &rarr;</a>
    </div>
  </div>
  {% endfor %}

  {% include "main/pagination.html" %}
{% endblock %}
        

templates/main/questions.html
{% extends "main/sample_base.html" %}

{% block heading %}Find Solved Questions{% endblock %}

{% block search_by_text %}
<form action="" method="POST">
  <div class="input-group">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Search questions" class="form-control">
    <input type="submit" value="Search" class="btn bg-dark-blue text-light">
  </div>
</form>
{% endblock %}

{% block search_by_dropdown %}
<form action="" method="POST">
  {% csrf_token %}
  <select class="form-select" name="categories" id="categories" onchange="submit_form(this)">
    <option selected>Select Categories</option>
    <option value="Macroeconomics">Macroeconomics</option>
    <option value="Organizational Behavior">Organizational Behavior</option>
    <option value="BBA Leadership">BBA Leadership</option>
    <option value="Strategic Human Resource Management">Strategic Human Resource Management</option>
    <option value="Customer Relationship Management">Customer Relationship Management</option>
    <option value="Training and Developement">Training and Development</option>
    <option value="Facts and Opinions">Facts and Opinions</option>
    <option value="The GCC Economics">The GCC Economics</option>
    <option value="Project Management">Project Management</option>
    <option value="Design Thinking">Design Thinking</option>
    <option value="Business Case">Business Case</option>
    <option value="Managerial Economics">Managerial Economics</option>
    <option value="Contemporary Issues in Strategic Management">Contemporary Issues in Strategic Management</option>
    <option value="Principles of Managerial Accounting">Principles of Managerial Accounting</option>
    <option value="Management Information Systems">Management Information Systems</option>
    <option value="Management">Management</option>
    <option value="HR">HR</option>
    <option value="Accounting">Accounting</option>
    <option value="Marketing">Marketing</option>
    <option value="Leadership">Leadership</option>
    <option value="BSC in Education Lesson Plan">BSC in Education Lesson Plan</option>
    <option value="Legal Aspect of Health Management">Legal Aspect of Health Management</option>
    <option value="CEI Reduce, Reuse and Recycle">CEI Reduce, Reuse and Recycle</option>
    <option value="Change Management">Change Management</option>
    <option value="Critical Review">Critical Review</option>
    <option value="International Perspective on Business">International Perspective on Business</option>
    <option value="Principles of Financial Accounting">Principles of Financial Accounting</option>
    <option value="Interactive Read Aloud">Interactive Read Aloud</option>
  </select>
</form>
{% endblock %}

{% block samples %}
  {% for object in object_list %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ object.heading|title }}</h5>
      {% with object.description as description %}
        {% if description %}
          <p class="card-text">{{ description }}</p>
        {% endif %}
      {% endwith %}
      <a class="float-end btn bg-blue fw-bold" href="{% url 'main:samples_detail' object.slug %}">More</a>
    </div>
  </div>
  {% endfor %}

  {% include "main/pagination.html" %}
{% endblock %}
        

templates/main/reviews_form.html
<form action="{% url 'main:submit-reviews' %}" method="POST">
  {% csrf_token %}
  <div class="modal fade" id="reviewsModal" tabindex="-1" aria-aria-labelledby="reviewsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header text-dark-blue">
          <h5>Write a Review</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" name="button"></button>
        </div>
        <div class="modal-body">
          <input class="form-control mb-2" type="text" name="title" placeholder="Enter Review Title">
          <input class="form-control mb-2" type="text" name="name" placeholder="Enter User Name">
          <input class="form-control mb-2" type="text" name="qualification" placeholder="Enter User Qualification">
          <!-- <input class="form-control mb-2" type="text" name="assignment_id" placeholder="Enter Assignment ID"> -->
          <select class="form-select mb-2" name="star">
            <option selected>Select Review Star</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
          <textarea name="description" class="form-control mb-2" rows="6" placeholder="Write Your Description"></textarea>
          <input type="submit" class="btn bg-dark-blue text-white" name="" value="Submit">
        </div>
      </div>
    </div>
  </div>
</form>

templates/main/sample_base.html
{% extends "main/base.html" %}

{% block content %}

<section class="container-fluid bg-light-blue">
  <div class="container">  
    <div class="row">
      <div class="col">
        <div class="text-center pt-5 pb-2 text-dark-blue">
          <h2>{% block heading %}{% endblock %}</h2>
        </div>
      </div>
    </div>

    <div class="row justify-content-center pb-4">
      <div class="col-lg-5">
        {% block search_by_text %}{% endblock %}
      </div>
      
      <div class="col-4">
        {% block search_by_dropdown %}{% endblock %}       
      </div>
      
    </div>
  </div>
</section>

<section class="container-fluid mt-4">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-6">
        <div class="row">
          {% block samples %}
          {% endblock %}
        </div>

      </div>

      <div class="col-lg-5 col-md-12">
        <div class="border rounded mt-sm-4 mt-3 mt-md-0 p-3 text-center">
          <h5>Hire Us Now</h5>
          {% include 'main/assignment_form.html' %}
        </div>
      </div>


    </div>
  </div>
</section>

{% endblock %}

templates/main/sample_details.html
{% extends "main/sample_base.html" %}

{% block heading %}Free Assignment Samples for UAE Students{% endblock %}

{% block search_by_text %}
<form action="{% url 'main:search_sample' %}" method="POST">
  <div class="input-group">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Search sample by text" class="form-control">
    <input type="submit" value="Search" class="btn bg-dark-blue text-light">
  </div>
</form>
{% endblock %}

{% block search_by_dropdown %}
<form action="{% url 'main:search_sample' %}" method="POST">
  {% csrf_token %}
  <select class="form-select" name="categories" id="categories" onchange="submit_form(this)">
    <option selected>Select Subject</option>
    <option value="IT">IT</option>
    <option value="Business Management">Business Management</option>
    <option value="General Education">General Education</option>
    <option value="Health Management">Health Management</option>
    <option value="Research Method">Research Method</option>
    <option value="Media">Media</option>
  </select>
</form>
{% endblock %}

{% block samples %}
<div class="card">
  <div class="card-body">
    <h3 class="card-title">{{ object.heading|title }}</h3>
    <p class="card-text">{{ object.description }}</p>
    {% for object in object.samples.all %}
      <p>
        <a href="{% url 'main:download' object %}">{{ object }}</a>
      </p>  
    {% endfor %}

    {% if object.url %}
      <p>
        <a href="{{ object.url }}" target="blank">{{ object.url }}</a>
      </p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/main/samples.html
{% extends "main/sample_base.html" %}

{% block heading %}
  Free Assignment Samples for UAE Students
{% endblock %}

{% block search_by_text %}
<form action="{% url 'main:search_sample' %}" method="POST">
  <div class="input-group">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Search sample by text" class="form-control">
    <input type="submit" value="Search" class="btn bg-dark-blue text-light">
  </div>
</form>
{% endblock %}

{% block search_by_dropdown %}
<form action="{% url 'main:search_sample' %}" method="POST">
  {% csrf_token %}
  <select class="form-select" name="categories" id="categories" onchange="submit_form(this)">
    <option selected>Select Subject</option>
    <option value="IT">IT</option>
    <option value="Business Management">Business Management</option>
    <option value="General Education">General Education</option>
    <option value="Health Management">Health Management</option>
    <option value="Research Method">Research Method</option>
    <option value="Media">Media</option>
  </select>
</form>
{% endblock %}

{% block samples %}
  {% for object in object_list %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ object.heading|title }}</h5>
      {% with object.description as description %}
        {% if description %}
          <p class="card-text">{{ description }}</p>
        {% endif %}
      {% endwith %}
      <a class="float-end btn bg-blue fw-bold" href="{% url 'main:samples_detail' object.slug %}">More</a>
    </div>
  </div>
  {% endfor %}

  {% include "main/pagination.html" %}
{% endblock %}
        

templates/main/success.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<main class="mt-5">
	<div class="container-fluid">
		<div class="container">
			<div class="row justify-content-center">
				
				<div class="col-md-6">
					<div class="text-center py-4">
						<img src="{% static 'images/checkmark.svg' %}" class="img-fluid w-25 shadow rounded-circle" alt="checkmark">
						<p class="fs-3 fw-bold">Success</p>
					</div>
				</div>
			</div>

			<div class="row justify-content-center">
				<div class="col-md-8">
					<div class="text-center p-3">
						<p class="fs-3">Hello <strong class="text-dark-blue">{{ name|title }}</strong></p>		
						<p class="">You have submitted your assignment successfully!</p>
	
						<p class="fw-light">
							We will send you the custom price quote over your email ID soon.
							If you have more assignments to submit just <a class="fw-bold" href="{% url 'main:submit-assignment' %}">Click Here</a> and upload new assignments easily.
							If you are in hurry and need urgent help, contact us at <a class="fw-bold" href="mailto:academicassistance4students@gmail.com">academicassistance4students@gmail.com</a>
						</p>
					</div>
				</div>
			</div>
		
		</div>
	</div>
</main>

{% endblock content %}